### ISSUE TITLE
[Question] Reading volume level

### ISSUE THREAD

**Issue by henrywintif** [mkulesh/onkyoUsbRi#1]
Hi @mkulesh reaching out as it seems you're the preeminent expert on the Onkyo A-9010. I'm curious if you've experimented hooking into JTAG and messing around with the firmware? I'm not very familiar with the process, but I'd like to get info back from my amplifier, which I don't think is possible using the RI input. Let me know any resources or otherwise I could look into. Regards,
Henry

**Comment by mkulesh** [comment]
Hi @henrywintif,
I have never used JTAG on my A-9010 and do not know any details about it. But I have a service manual for this amplifier. In this manual, there is a complete schematic including JTAG (see page 8):
[A-9010 Service manual.pdf](https://github.com/mkulesh/onkyoUsbRi/files/11995480/A-9010.Service.manual.pdf)
My A-9010 is based on Infineon MB9AF342NAPMC MCU, the datasheet with JTAG description for it is also available: https://www.datasheets.com/en/part-details/mb9af342napmc-infineon-technologies-ag-54688575#datasheet
I hope this can help you.

**Comment by henrywintif** [comment]
Thank you! I will report back if I'm able to get any interesting information out of the system.
